### PR TITLE
Migrate bitcoincashjs to bitcoincashjs-fork.

### PR DESCRIPTION
**Pull request by jbdtky**

### CODE REVIEW

**Comment by jbdtky** [comment]
https://www.npmjs.com/package/bitcoincashjs-fork
https://www.npmjs.com/package/cashaddrjs-fork

**Comment by brendoncoin** [comment]
The forks could do with some more descriptive names that gives some clue about why they were created. It would be good to include that information in the readmes too.

**Comment by jbdtky** [comment]
No error is founded in the emulator logs. So lets investigate why 👍

**Comment by jbdtky** [comment]
Works well. Thanks for fixing the duplication. However, we are considering this issue like a hotfix. This pull request will be closed and a new PR will be created to the hotfix branch.

**Pull request closed without merging**
