### PR TITLE
Fix for #337: Also check if Cordova is loaded.. Debugging with the device toolbar breaks…

### PR DESCRIPTION
**Pull request by spasma**
…as it exposes itself as android, and without StatusBar defined.

### CODE REVIEW

**Comment by jbdtky** [comment]
It is working on android device without this change.

**Comment by brendoncoin** [comment]
Works fine on the Android emulator on my machine, without this change. After discussion with @jbdtky , I'm closing this as unnecessary.

**Comment by sagech** [comment]
Can confirm that it works fine on my real Android device.

**Comment by spasma** [comment]
This issue was not regarding the Android emulator, I meant the Device toolbar in the Google Chrome console (which emulates the user agent, so you can simulate the device specific css/code)

**Pull request closed without merging**
